/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBaRouteImport } from './routes/_authenticated/ba'
import { Route as AuthenticatedBaReportRouteImport } from './routes/_authenticated/ba-report'
import { Route as AuthenticatedBulkReviewRouteImport } from './routes/_authenticated/bulk-review'
import { Route as AuthenticatedBusinessReportsRouteImport } from './routes/_authenticated/business-reports'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedCompanyPurchaseRouteImport } from './routes/_authenticated/company-purchase'
import { Route as AuthenticatedCsaRouteImport } from './routes/_authenticated/csa'
import { Route as AuthenticatedDeliveryNoteRouteImport } from './routes/_authenticated/delivery-note'
import { Route as AuthenticatedDepotRouteImport } from './routes/_authenticated/depot'
import { Route as AuthenticatedDepotPurchaseRouteImport } from './routes/_authenticated/depot-purchase'
import { Route as AuthenticatedDistributorRouteImport } from './routes/_authenticated/distributor'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedGodownSaleRouteImport } from './routes/_authenticated/godown-sale'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedLiveMapRouteImport } from './routes/_authenticated/live-map'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedMyReportRouteImport } from './routes/_authenticated/my-report'
import { Route as AuthenticatedOfficeRouteImport } from './routes/_authenticated/office'
import { Route as AuthenticatedOfficeManagerRouteImport } from './routes/_authenticated/office-manager'
import { Route as AuthenticatedOpeningStockRouteImport } from './routes/_authenticated/opening-stock'
import { Route as AuthenticatedOrderBookingRouteImport } from './routes/_authenticated/order-booking'
import { Route as AuthenticatedPaymentInRouteImport } from './routes/_authenticated/payment-in'
import { Route as AuthenticatedPaymentOutRouteImport } from './routes/_authenticated/payment-out'
import { Route as AuthenticatedPurchaseOrderRouteImport } from './routes/_authenticated/purchase-order'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesmanRouteImport } from './routes/_authenticated/salesman'
import { Route as AuthenticatedStockAdjustRouteImport } from './routes/_authenticated/stock-adjust'
import { Route as AuthenticatedAdminCsaIdRouteImport } from './routes/_authenticated/admin-csa.$id'
import { Route as AuthenticatedAdminReportCardRouteImport } from './routes/_authenticated/admin-report.$card'
import { Route as AuthenticatedBusinessReportCardRouteImport } from './routes/_authenticated/business-report.$card'
import { Route as AuthenticatedCsaReportCardRouteImport } from './routes/_authenticated/csa-report.$card'
import { Route as AuthenticatedDepotOrderOrderIdRouteImport } from './routes/_authenticated/depot-order.$orderId'
import { Route as AuthenticatedDepotReportCardRouteImport } from './routes/_authenticated/depot-report.$card'
import { Route as AuthenticatedDistributorNetworkIdRouteImport } from './routes/_authenticated/distributor-network.$id'
import { Route as AuthenticatedDistributorReportCardRouteImport } from './routes/_authenticated/distributor-report.$card'
import { Route as AuthenticatedHrReportCardRouteImport } from './routes/_authenticated/hr-report.$card'
import { Route as AuthenticatedMarginReportMetricRouteImport } from './routes/_authenticated/margin-report.$metric'
import { Route as AuthenticatedOrderOrderIdRouteImport } from './routes/_authenticated/order.$orderId'
import { Route as AuthenticatedPartyLedgerIndexRouteImport } from './routes/_authenticated/party-ledger.index'
import { Route as AuthenticatedPrimaryOrderOrderIdRouteImport } from './routes/_authenticated/primary-order.$orderId'
import { Route as AuthenticatedReportDetailSectionRouteImport } from './routes/_authenticated/report-detail.$section'
import { Route as AuthenticatedSalesmanReportCardRouteImport } from './routes/_authenticated/salesman-report.$card'
import { Route as AuthenticatedPartyLedgerTypeIdRouteImport } from './routes/_authenticated/party-ledger.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaRoute = AuthenticatedBaRouteImport.update({
  id: '/ba',
  path: '/ba',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaReportRoute = AuthenticatedBaReportRouteImport.update({
  id: '/ba-report',
  path: '/ba-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkReviewRoute = AuthenticatedBulkReviewRouteImport.update({
  id: '/bulk-review',
  path: '/bulk-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessReportsRoute =
  AuthenticatedBusinessReportsRouteImport.update({
    id: '/business-reports',
    path: '/business-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyPurchaseRoute =
  AuthenticatedCompanyPurchaseRouteImport.update({
    id: '/company-purchase',
    path: '/company-purchase',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCsaRoute = AuthenticatedCsaRouteImport.update({
  id: '/csa',
  path: '/csa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryNoteRoute =
  AuthenticatedDeliveryNoteRouteImport.update({
    id: '/delivery-note',
    path: '/delivery-note',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepotRoute = AuthenticatedDepotRouteImport.update({
  id: '/depot',
  path: '/depot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepotPurchaseRoute =
  AuthenticatedDepotPurchaseRouteImport.update({
    id: '/depot-purchase',
    path: '/depot-purchase',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributorRoute =
  AuthenticatedDistributorRouteImport.update({
    id: '/distributor',
    path: '/distributor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGodownSaleRoute = AuthenticatedGodownSaleRouteImport.update({
  id: '/godown-sale',
  path: '/godown-sale',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveMapRoute = AuthenticatedLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyReportRoute = AuthenticatedMyReportRouteImport.update({
  id: '/my-report',
  path: '/my-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficeRoute = AuthenticatedOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficeManagerRoute =
  AuthenticatedOfficeManagerRouteImport.update({
    id: '/office-manager',
    path: '/office-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpeningStockRoute =
  AuthenticatedOpeningStockRouteImport.update({
    id: '/opening-stock',
    path: '/opening-stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderBookingRoute =
  AuthenticatedOrderBookingRouteImport.update({
    id: '/order-booking',
    path: '/order-booking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentInRoute = AuthenticatedPaymentInRouteImport.update({
  id: '/payment-in',
  path: '/payment-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentOutRoute = AuthenticatedPaymentOutRouteImport.update({
  id: '/payment-out',
  path: '/payment-out',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrderRoute =
  AuthenticatedPurchaseOrderRouteImport.update({
    id: '/purchase-order',
    path: '/purchase-order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesmanRoute = AuthenticatedSalesmanRouteImport.update({
  id: '/salesman',
  path: '/salesman',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockAdjustRoute =
  AuthenticatedStockAdjustRouteImport.update({
    id: '/stock-adjust',
    path: '/stock-adjust',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCsaIdRoute = AuthenticatedAdminCsaIdRouteImport.update({
  id: '/admin-csa/$id',
  path: '/admin-csa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportCardRoute =
  AuthenticatedAdminReportCardRouteImport.update({
    id: '/admin-report/$card',
    path: '/admin-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessReportCardRoute =
  AuthenticatedBusinessReportCardRouteImport.update({
    id: '/business-report/$card',
    path: '/business-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCsaReportCardRoute =
  AuthenticatedCsaReportCardRouteImport.update({
    id: '/csa-report/$card',
    path: '/csa-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepotOrderOrderIdRoute =
  AuthenticatedDepotOrderOrderIdRouteImport.update({
    id: '/depot-order/$orderId',
    path: '/depot-order/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepotReportCardRoute =
  AuthenticatedDepotReportCardRouteImport.update({
    id: '/depot-report/$card',
    path: '/depot-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributorNetworkIdRoute =
  AuthenticatedDistributorNetworkIdRouteImport.update({
    id: '/distributor-network/$id',
    path: '/distributor-network/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributorReportCardRoute =
  AuthenticatedDistributorReportCardRouteImport.update({
    id: '/distributor-report/$card',
    path: '/distributor-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrReportCardRoute =
  AuthenticatedHrReportCardRouteImport.update({
    id: '/hr-report/$card',
    path: '/hr-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarginReportMetricRoute =
  AuthenticatedMarginReportMetricRouteImport.update({
    id: '/margin-report/$metric',
    path: '/margin-report/$metric',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderOrderIdRoute =
  AuthenticatedOrderOrderIdRouteImport.update({
    id: '/order/$orderId',
    path: '/order/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartyLedgerIndexRoute =
  AuthenticatedPartyLedgerIndexRouteImport.update({
    id: '/party-ledger/',
    path: '/party-ledger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrimaryOrderOrderIdRoute =
  AuthenticatedPrimaryOrderOrderIdRouteImport.update({
    id: '/primary-order/$orderId',
    path: '/primary-order/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportDetailSectionRoute =
  AuthenticatedReportDetailSectionRouteImport.update({
    id: '/report-detail/$section',
    path: '/report-detail/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesmanReportCardRoute =
  AuthenticatedSalesmanReportCardRouteImport.update({
    id: '/salesman-report/$card',
    path: '/salesman-report/$card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartyLedgerTypeIdRoute =
  AuthenticatedPartyLedgerTypeIdRouteImport.update({
    id: '/party-ledger/$type/$id',
    path: '/party-ledger/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ba': typeof AuthenticatedBaRoute
  '/ba-report': typeof AuthenticatedBaReportRoute
  '/bulk-review': typeof AuthenticatedBulkReviewRoute
  '/business-reports': typeof AuthenticatedBusinessReportsRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/company-purchase': typeof AuthenticatedCompanyPurchaseRoute
  '/csa': typeof AuthenticatedCsaRoute
  '/delivery-note': typeof AuthenticatedDeliveryNoteRoute
  '/depot': typeof AuthenticatedDepotRoute
  '/depot-purchase': typeof AuthenticatedDepotPurchaseRoute
  '/distributor': typeof AuthenticatedDistributorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/godown-sale': typeof AuthenticatedGodownSaleRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hr': typeof AuthenticatedHrRoute
  '/live-map': typeof AuthenticatedLiveMapRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/my-report': typeof AuthenticatedMyReportRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/office-manager': typeof AuthenticatedOfficeManagerRoute
  '/opening-stock': typeof AuthenticatedOpeningStockRoute
  '/order-booking': typeof AuthenticatedOrderBookingRoute
  '/payment-in': typeof AuthenticatedPaymentInRoute
  '/payment-out': typeof AuthenticatedPaymentOutRoute
  '/purchase-order': typeof AuthenticatedPurchaseOrderRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/salesman': typeof AuthenticatedSalesmanRoute
  '/stock-adjust': typeof AuthenticatedStockAdjustRoute
  '/admin-csa/$id': typeof AuthenticatedAdminCsaIdRoute
  '/admin-report/$card': typeof AuthenticatedAdminReportCardRoute
  '/business-report/$card': typeof AuthenticatedBusinessReportCardRoute
  '/csa-report/$card': typeof AuthenticatedCsaReportCardRoute
  '/depot-order/$orderId': typeof AuthenticatedDepotOrderOrderIdRoute
  '/depot-report/$card': typeof AuthenticatedDepotReportCardRoute
  '/distributor-network/$id': typeof AuthenticatedDistributorNetworkIdRoute
  '/distributor-report/$card': typeof AuthenticatedDistributorReportCardRoute
  '/hr-report/$card': typeof AuthenticatedHrReportCardRoute
  '/margin-report/$metric': typeof AuthenticatedMarginReportMetricRoute
  '/order/$orderId': typeof AuthenticatedOrderOrderIdRoute
  '/primary-order/$orderId': typeof AuthenticatedPrimaryOrderOrderIdRoute
  '/report-detail/$section': typeof AuthenticatedReportDetailSectionRoute
  '/salesman-report/$card': typeof AuthenticatedSalesmanReportCardRoute
  '/party-ledger/': typeof AuthenticatedPartyLedgerIndexRoute
  '/party-ledger/$type/$id': typeof AuthenticatedPartyLedgerTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ba': typeof AuthenticatedBaRoute
  '/ba-report': typeof AuthenticatedBaReportRoute
  '/bulk-review': typeof AuthenticatedBulkReviewRoute
  '/business-reports': typeof AuthenticatedBusinessReportsRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/company-purchase': typeof AuthenticatedCompanyPurchaseRoute
  '/csa': typeof AuthenticatedCsaRoute
  '/delivery-note': typeof AuthenticatedDeliveryNoteRoute
  '/depot': typeof AuthenticatedDepotRoute
  '/depot-purchase': typeof AuthenticatedDepotPurchaseRoute
  '/distributor': typeof AuthenticatedDistributorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/godown-sale': typeof AuthenticatedGodownSaleRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hr': typeof AuthenticatedHrRoute
  '/live-map': typeof AuthenticatedLiveMapRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/my-report': typeof AuthenticatedMyReportRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/office-manager': typeof AuthenticatedOfficeManagerRoute
  '/opening-stock': typeof AuthenticatedOpeningStockRoute
  '/order-booking': typeof AuthenticatedOrderBookingRoute
  '/payment-in': typeof AuthenticatedPaymentInRoute
  '/payment-out': typeof AuthenticatedPaymentOutRoute
  '/purchase-order': typeof AuthenticatedPurchaseOrderRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/salesman': typeof AuthenticatedSalesmanRoute
  '/stock-adjust': typeof AuthenticatedStockAdjustRoute
  '/admin-csa/$id': typeof AuthenticatedAdminCsaIdRoute
  '/admin-report/$card': typeof AuthenticatedAdminReportCardRoute
  '/business-report/$card': typeof AuthenticatedBusinessReportCardRoute
  '/csa-report/$card': typeof AuthenticatedCsaReportCardRoute
  '/depot-order/$orderId': typeof AuthenticatedDepotOrderOrderIdRoute
  '/depot-report/$card': typeof AuthenticatedDepotReportCardRoute
  '/distributor-network/$id': typeof AuthenticatedDistributorNetworkIdRoute
  '/distributor-report/$card': typeof AuthenticatedDistributorReportCardRoute
  '/hr-report/$card': typeof AuthenticatedHrReportCardRoute
  '/margin-report/$metric': typeof AuthenticatedMarginReportMetricRoute
  '/order/$orderId': typeof AuthenticatedOrderOrderIdRoute
  '/primary-order/$orderId': typeof AuthenticatedPrimaryOrderOrderIdRoute
  '/report-detail/$section': typeof AuthenticatedReportDetailSectionRoute
  '/salesman-report/$card': typeof AuthenticatedSalesmanReportCardRoute
  '/party-ledger': typeof AuthenticatedPartyLedgerIndexRoute
  '/party-ledger/$type/$id': typeof AuthenticatedPartyLedgerTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ba': typeof AuthenticatedBaRoute
  '/_authenticated/ba-report': typeof AuthenticatedBaReportRoute
  '/_authenticated/bulk-review': typeof AuthenticatedBulkReviewRoute
  '/_authenticated/business-reports': typeof AuthenticatedBusinessReportsRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/company-purchase': typeof AuthenticatedCompanyPurchaseRoute
  '/_authenticated/csa': typeof AuthenticatedCsaRoute
  '/_authenticated/delivery-note': typeof AuthenticatedDeliveryNoteRoute
  '/_authenticated/depot': typeof AuthenticatedDepotRoute
  '/_authenticated/depot-purchase': typeof AuthenticatedDepotPurchaseRoute
  '/_authenticated/distributor': typeof AuthenticatedDistributorRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/godown-sale': typeof AuthenticatedGodownSaleRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/live-map': typeof AuthenticatedLiveMapRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/my-report': typeof AuthenticatedMyReportRoute
  '/_authenticated/office': typeof AuthenticatedOfficeRoute
  '/_authenticated/office-manager': typeof AuthenticatedOfficeManagerRoute
  '/_authenticated/opening-stock': typeof AuthenticatedOpeningStockRoute
  '/_authenticated/order-booking': typeof AuthenticatedOrderBookingRoute
  '/_authenticated/payment-in': typeof AuthenticatedPaymentInRoute
  '/_authenticated/payment-out': typeof AuthenticatedPaymentOutRoute
  '/_authenticated/purchase-order': typeof AuthenticatedPurchaseOrderRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/salesman': typeof AuthenticatedSalesmanRoute
  '/_authenticated/stock-adjust': typeof AuthenticatedStockAdjustRoute
  '/_authenticated/admin-csa/$id': typeof AuthenticatedAdminCsaIdRoute
  '/_authenticated/admin-report/$card': typeof AuthenticatedAdminReportCardRoute
  '/_authenticated/business-report/$card': typeof AuthenticatedBusinessReportCardRoute
  '/_authenticated/csa-report/$card': typeof AuthenticatedCsaReportCardRoute
  '/_authenticated/depot-order/$orderId': typeof AuthenticatedDepotOrderOrderIdRoute
  '/_authenticated/depot-report/$card': typeof AuthenticatedDepotReportCardRoute
  '/_authenticated/distributor-network/$id': typeof AuthenticatedDistributorNetworkIdRoute
  '/_authenticated/distributor-report/$card': typeof AuthenticatedDistributorReportCardRoute
  '/_authenticated/hr-report/$card': typeof AuthenticatedHrReportCardRoute
  '/_authenticated/margin-report/$metric': typeof AuthenticatedMarginReportMetricRoute
  '/_authenticated/order/$orderId': typeof AuthenticatedOrderOrderIdRoute
  '/_authenticated/primary-order/$orderId': typeof AuthenticatedPrimaryOrderOrderIdRoute
  '/_authenticated/report-detail/$section': typeof AuthenticatedReportDetailSectionRoute
  '/_authenticated/salesman-report/$card': typeof AuthenticatedSalesmanReportCardRoute
  '/_authenticated/party-ledger/': typeof AuthenticatedPartyLedgerIndexRoute
  '/_authenticated/party-ledger/$type/$id': typeof AuthenticatedPartyLedgerTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/ba'
    | '/ba-report'
    | '/bulk-review'
    | '/business-reports'
    | '/claims'
    | '/company-purchase'
    | '/csa'
    | '/delivery-note'
    | '/depot'
    | '/depot-purchase'
    | '/distributor'
    | '/expenses'
    | '/godown-sale'
    | '/home'
    | '/hr'
    | '/live-map'
    | '/manager'
    | '/my-report'
    | '/office'
    | '/office-manager'
    | '/opening-stock'
    | '/order-booking'
    | '/payment-in'
    | '/payment-out'
    | '/purchase-order'
    | '/reports'
    | '/salesman'
    | '/stock-adjust'
    | '/admin-csa/$id'
    | '/admin-report/$card'
    | '/business-report/$card'
    | '/csa-report/$card'
    | '/depot-order/$orderId'
    | '/depot-report/$card'
    | '/distributor-network/$id'
    | '/distributor-report/$card'
    | '/hr-report/$card'
    | '/margin-report/$metric'
    | '/order/$orderId'
    | '/primary-order/$orderId'
    | '/report-detail/$section'
    | '/salesman-report/$card'
    | '/party-ledger/'
    | '/party-ledger/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/ba'
    | '/ba-report'
    | '/bulk-review'
    | '/business-reports'
    | '/claims'
    | '/company-purchase'
    | '/csa'
    | '/delivery-note'
    | '/depot'
    | '/depot-purchase'
    | '/distributor'
    | '/expenses'
    | '/godown-sale'
    | '/home'
    | '/hr'
    | '/live-map'
    | '/manager'
    | '/my-report'
    | '/office'
    | '/office-manager'
    | '/opening-stock'
    | '/order-booking'
    | '/payment-in'
    | '/payment-out'
    | '/purchase-order'
    | '/reports'
    | '/salesman'
    | '/stock-adjust'
    | '/admin-csa/$id'
    | '/admin-report/$card'
    | '/business-report/$card'
    | '/csa-report/$card'
    | '/depot-order/$orderId'
    | '/depot-report/$card'
    | '/distributor-network/$id'
    | '/distributor-report/$card'
    | '/hr-report/$card'
    | '/margin-report/$metric'
    | '/order/$orderId'
    | '/primary-order/$orderId'
    | '/report-detail/$section'
    | '/salesman-report/$card'
    | '/party-ledger'
    | '/party-ledger/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/ba'
    | '/_authenticated/ba-report'
    | '/_authenticated/bulk-review'
    | '/_authenticated/business-reports'
    | '/_authenticated/claims'
    | '/_authenticated/company-purchase'
    | '/_authenticated/csa'
    | '/_authenticated/delivery-note'
    | '/_authenticated/depot'
    | '/_authenticated/depot-purchase'
    | '/_authenticated/distributor'
    | '/_authenticated/expenses'
    | '/_authenticated/godown-sale'
    | '/_authenticated/home'
    | '/_authenticated/hr'
    | '/_authenticated/live-map'
    | '/_authenticated/manager'
    | '/_authenticated/my-report'
    | '/_authenticated/office'
    | '/_authenticated/office-manager'
    | '/_authenticated/opening-stock'
    | '/_authenticated/order-booking'
    | '/_authenticated/payment-in'
    | '/_authenticated/payment-out'
    | '/_authenticated/purchase-order'
    | '/_authenticated/reports'
    | '/_authenticated/salesman'
    | '/_authenticated/stock-adjust'
    | '/_authenticated/admin-csa/$id'
    | '/_authenticated/admin-report/$card'
    | '/_authenticated/business-report/$card'
    | '/_authenticated/csa-report/$card'
    | '/_authenticated/depot-order/$orderId'
    | '/_authenticated/depot-report/$card'
    | '/_authenticated/distributor-network/$id'
    | '/_authenticated/distributor-report/$card'
    | '/_authenticated/hr-report/$card'
    | '/_authenticated/margin-report/$metric'
    | '/_authenticated/order/$orderId'
    | '/_authenticated/primary-order/$orderId'
    | '/_authenticated/report-detail/$section'
    | '/_authenticated/salesman-report/$card'
    | '/_authenticated/party-ledger/'
    | '/_authenticated/party-ledger/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ba': {
      id: '/_authenticated/ba'
      path: '/ba'
      fullPath: '/ba'
      preLoaderRoute: typeof AuthenticatedBaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ba-report': {
      id: '/_authenticated/ba-report'
      path: '/ba-report'
      fullPath: '/ba-report'
      preLoaderRoute: typeof AuthenticatedBaReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk-review': {
      id: '/_authenticated/bulk-review'
      path: '/bulk-review'
      fullPath: '/bulk-review'
      preLoaderRoute: typeof AuthenticatedBulkReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-reports': {
      id: '/_authenticated/business-reports'
      path: '/business-reports'
      fullPath: '/business-reports'
      preLoaderRoute: typeof AuthenticatedBusinessReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-purchase': {
      id: '/_authenticated/company-purchase'
      path: '/company-purchase'
      fullPath: '/company-purchase'
      preLoaderRoute: typeof AuthenticatedCompanyPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/csa': {
      id: '/_authenticated/csa'
      path: '/csa'
      fullPath: '/csa'
      preLoaderRoute: typeof AuthenticatedCsaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-note': {
      id: '/_authenticated/delivery-note'
      path: '/delivery-note'
      fullPath: '/delivery-note'
      preLoaderRoute: typeof AuthenticatedDeliveryNoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depot': {
      id: '/_authenticated/depot'
      path: '/depot'
      fullPath: '/depot'
      preLoaderRoute: typeof AuthenticatedDepotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depot-purchase': {
      id: '/_authenticated/depot-purchase'
      path: '/depot-purchase'
      fullPath: '/depot-purchase'
      preLoaderRoute: typeof AuthenticatedDepotPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distributor': {
      id: '/_authenticated/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof AuthenticatedDistributorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/godown-sale': {
      id: '/_authenticated/godown-sale'
      path: '/godown-sale'
      fullPath: '/godown-sale'
      preLoaderRoute: typeof AuthenticatedGodownSaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-map': {
      id: '/_authenticated/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof AuthenticatedLiveMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-report': {
      id: '/_authenticated/my-report'
      path: '/my-report'
      fullPath: '/my-report'
      preLoaderRoute: typeof AuthenticatedMyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office': {
      id: '/_authenticated/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof AuthenticatedOfficeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office-manager': {
      id: '/_authenticated/office-manager'
      path: '/office-manager'
      fullPath: '/office-manager'
      preLoaderRoute: typeof AuthenticatedOfficeManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opening-stock': {
      id: '/_authenticated/opening-stock'
      path: '/opening-stock'
      fullPath: '/opening-stock'
      preLoaderRoute: typeof AuthenticatedOpeningStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-booking': {
      id: '/_authenticated/order-booking'
      path: '/order-booking'
      fullPath: '/order-booking'
      preLoaderRoute: typeof AuthenticatedOrderBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-in': {
      id: '/_authenticated/payment-in'
      path: '/payment-in'
      fullPath: '/payment-in'
      preLoaderRoute: typeof AuthenticatedPaymentInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-out': {
      id: '/_authenticated/payment-out'
      path: '/payment-out'
      fullPath: '/payment-out'
      preLoaderRoute: typeof AuthenticatedPaymentOutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-order': {
      id: '/_authenticated/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof AuthenticatedPurchaseOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salesman': {
      id: '/_authenticated/salesman'
      path: '/salesman'
      fullPath: '/salesman'
      preLoaderRoute: typeof AuthenticatedSalesmanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-adjust': {
      id: '/_authenticated/stock-adjust'
      path: '/stock-adjust'
      fullPath: '/stock-adjust'
      preLoaderRoute: typeof AuthenticatedStockAdjustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-csa/$id': {
      id: '/_authenticated/admin-csa/$id'
      path: '/admin-csa/$id'
      fullPath: '/admin-csa/$id'
      preLoaderRoute: typeof AuthenticatedAdminCsaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-report/$card': {
      id: '/_authenticated/admin-report/$card'
      path: '/admin-report/$card'
      fullPath: '/admin-report/$card'
      preLoaderRoute: typeof AuthenticatedAdminReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-report/$card': {
      id: '/_authenticated/business-report/$card'
      path: '/business-report/$card'
      fullPath: '/business-report/$card'
      preLoaderRoute: typeof AuthenticatedBusinessReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/csa-report/$card': {
      id: '/_authenticated/csa-report/$card'
      path: '/csa-report/$card'
      fullPath: '/csa-report/$card'
      preLoaderRoute: typeof AuthenticatedCsaReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depot-order/$orderId': {
      id: '/_authenticated/depot-order/$orderId'
      path: '/depot-order/$orderId'
      fullPath: '/depot-order/$orderId'
      preLoaderRoute: typeof AuthenticatedDepotOrderOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depot-report/$card': {
      id: '/_authenticated/depot-report/$card'
      path: '/depot-report/$card'
      fullPath: '/depot-report/$card'
      preLoaderRoute: typeof AuthenticatedDepotReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distributor-network/$id': {
      id: '/_authenticated/distributor-network/$id'
      path: '/distributor-network/$id'
      fullPath: '/distributor-network/$id'
      preLoaderRoute: typeof AuthenticatedDistributorNetworkIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distributor-report/$card': {
      id: '/_authenticated/distributor-report/$card'
      path: '/distributor-report/$card'
      fullPath: '/distributor-report/$card'
      preLoaderRoute: typeof AuthenticatedDistributorReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-report/$card': {
      id: '/_authenticated/hr-report/$card'
      path: '/hr-report/$card'
      fullPath: '/hr-report/$card'
      preLoaderRoute: typeof AuthenticatedHrReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/margin-report/$metric': {
      id: '/_authenticated/margin-report/$metric'
      path: '/margin-report/$metric'
      fullPath: '/margin-report/$metric'
      preLoaderRoute: typeof AuthenticatedMarginReportMetricRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/$orderId': {
      id: '/_authenticated/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AuthenticatedOrderOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party-ledger/': {
      id: '/_authenticated/party-ledger/'
      path: '/party-ledger'
      fullPath: '/party-ledger/'
      preLoaderRoute: typeof AuthenticatedPartyLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/primary-order/$orderId': {
      id: '/_authenticated/primary-order/$orderId'
      path: '/primary-order/$orderId'
      fullPath: '/primary-order/$orderId'
      preLoaderRoute: typeof AuthenticatedPrimaryOrderOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-detail/$section': {
      id: '/_authenticated/report-detail/$section'
      path: '/report-detail/$section'
      fullPath: '/report-detail/$section'
      preLoaderRoute: typeof AuthenticatedReportDetailSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salesman-report/$card': {
      id: '/_authenticated/salesman-report/$card'
      path: '/salesman-report/$card'
      fullPath: '/salesman-report/$card'
      preLoaderRoute: typeof AuthenticatedSalesmanReportCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party-ledger/$type/$id': {
      id: '/_authenticated/party-ledger/$type/$id'
      path: '/party-ledger/$type/$id'
      fullPath: '/party-ledger/$type/$id'
      preLoaderRoute: typeof AuthenticatedPartyLedgerTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBaRoute: typeof AuthenticatedBaRoute
  AuthenticatedBaReportRoute: typeof AuthenticatedBaReportRoute
  AuthenticatedBulkReviewRoute: typeof AuthenticatedBulkReviewRoute
  AuthenticatedBusinessReportsRoute: typeof AuthenticatedBusinessReportsRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedCompanyPurchaseRoute: typeof AuthenticatedCompanyPurchaseRoute
  AuthenticatedCsaRoute: typeof AuthenticatedCsaRoute
  AuthenticatedDeliveryNoteRoute: typeof AuthenticatedDeliveryNoteRoute
  AuthenticatedDepotRoute: typeof AuthenticatedDepotRoute
  AuthenticatedDepotPurchaseRoute: typeof AuthenticatedDepotPurchaseRoute
  AuthenticatedDistributorRoute: typeof AuthenticatedDistributorRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGodownSaleRoute: typeof AuthenticatedGodownSaleRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedLiveMapRoute: typeof AuthenticatedLiveMapRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedMyReportRoute: typeof AuthenticatedMyReportRoute
  AuthenticatedOfficeRoute: typeof AuthenticatedOfficeRoute
  AuthenticatedOfficeManagerRoute: typeof AuthenticatedOfficeManagerRoute
  AuthenticatedOpeningStockRoute: typeof AuthenticatedOpeningStockRoute
  AuthenticatedOrderBookingRoute: typeof AuthenticatedOrderBookingRoute
  AuthenticatedPaymentInRoute: typeof AuthenticatedPaymentInRoute
  AuthenticatedPaymentOutRoute: typeof AuthenticatedPaymentOutRoute
  AuthenticatedPurchaseOrderRoute: typeof AuthenticatedPurchaseOrderRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesmanRoute: typeof AuthenticatedSalesmanRoute
  AuthenticatedStockAdjustRoute: typeof AuthenticatedStockAdjustRoute
  AuthenticatedAdminCsaIdRoute: typeof AuthenticatedAdminCsaIdRoute
  AuthenticatedAdminReportCardRoute: typeof AuthenticatedAdminReportCardRoute
  AuthenticatedBusinessReportCardRoute: typeof AuthenticatedBusinessReportCardRoute
  AuthenticatedCsaReportCardRoute: typeof AuthenticatedCsaReportCardRoute
  AuthenticatedDepotOrderOrderIdRoute: typeof AuthenticatedDepotOrderOrderIdRoute
  AuthenticatedDepotReportCardRoute: typeof AuthenticatedDepotReportCardRoute
  AuthenticatedDistributorNetworkIdRoute: typeof AuthenticatedDistributorNetworkIdRoute
  AuthenticatedDistributorReportCardRoute: typeof AuthenticatedDistributorReportCardRoute
  AuthenticatedHrReportCardRoute: typeof AuthenticatedHrReportCardRoute
  AuthenticatedMarginReportMetricRoute: typeof AuthenticatedMarginReportMetricRoute
  AuthenticatedOrderOrderIdRoute: typeof AuthenticatedOrderOrderIdRoute
  AuthenticatedPrimaryOrderOrderIdRoute: typeof AuthenticatedPrimaryOrderOrderIdRoute
  AuthenticatedReportDetailSectionRoute: typeof AuthenticatedReportDetailSectionRoute
  AuthenticatedSalesmanReportCardRoute: typeof AuthenticatedSalesmanReportCardRoute
  AuthenticatedPartyLedgerIndexRoute: typeof AuthenticatedPartyLedgerIndexRoute
  AuthenticatedPartyLedgerTypeIdRoute: typeof AuthenticatedPartyLedgerTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBaRoute: AuthenticatedBaRoute,
  AuthenticatedBaReportRoute: AuthenticatedBaReportRoute,
  AuthenticatedBulkReviewRoute: AuthenticatedBulkReviewRoute,
  AuthenticatedBusinessReportsRoute: AuthenticatedBusinessReportsRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedCompanyPurchaseRoute: AuthenticatedCompanyPurchaseRoute,
  AuthenticatedCsaRoute: AuthenticatedCsaRoute,
  AuthenticatedDeliveryNoteRoute: AuthenticatedDeliveryNoteRoute,
  AuthenticatedDepotRoute: AuthenticatedDepotRoute,
  AuthenticatedDepotPurchaseRoute: AuthenticatedDepotPurchaseRoute,
  AuthenticatedDistributorRoute: AuthenticatedDistributorRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGodownSaleRoute: AuthenticatedGodownSaleRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedLiveMapRoute: AuthenticatedLiveMapRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedMyReportRoute: AuthenticatedMyReportRoute,
  AuthenticatedOfficeRoute: AuthenticatedOfficeRoute,
  AuthenticatedOfficeManagerRoute: AuthenticatedOfficeManagerRoute,
  AuthenticatedOpeningStockRoute: AuthenticatedOpeningStockRoute,
  AuthenticatedOrderBookingRoute: AuthenticatedOrderBookingRoute,
  AuthenticatedPaymentInRoute: AuthenticatedPaymentInRoute,
  AuthenticatedPaymentOutRoute: AuthenticatedPaymentOutRoute,
  AuthenticatedPurchaseOrderRoute: AuthenticatedPurchaseOrderRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesmanRoute: AuthenticatedSalesmanRoute,
  AuthenticatedStockAdjustRoute: AuthenticatedStockAdjustRoute,
  AuthenticatedAdminCsaIdRoute: AuthenticatedAdminCsaIdRoute,
  AuthenticatedAdminReportCardRoute: AuthenticatedAdminReportCardRoute,
  AuthenticatedBusinessReportCardRoute: AuthenticatedBusinessReportCardRoute,
  AuthenticatedCsaReportCardRoute: AuthenticatedCsaReportCardRoute,
  AuthenticatedDepotOrderOrderIdRoute: AuthenticatedDepotOrderOrderIdRoute,
  AuthenticatedDepotReportCardRoute: AuthenticatedDepotReportCardRoute,
  AuthenticatedDistributorNetworkIdRoute:
    AuthenticatedDistributorNetworkIdRoute,
  AuthenticatedDistributorReportCardRoute:
    AuthenticatedDistributorReportCardRoute,
  AuthenticatedHrReportCardRoute: AuthenticatedHrReportCardRoute,
  AuthenticatedMarginReportMetricRoute: AuthenticatedMarginReportMetricRoute,
  AuthenticatedOrderOrderIdRoute: AuthenticatedOrderOrderIdRoute,
  AuthenticatedPrimaryOrderOrderIdRoute: AuthenticatedPrimaryOrderOrderIdRoute,
  AuthenticatedReportDetailSectionRoute: AuthenticatedReportDetailSectionRoute,
  AuthenticatedSalesmanReportCardRoute: AuthenticatedSalesmanReportCardRoute,
  AuthenticatedPartyLedgerIndexRoute: AuthenticatedPartyLedgerIndexRoute,
  AuthenticatedPartyLedgerTypeIdRoute: AuthenticatedPartyLedgerTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
